# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getPillai <- function(Sw, St, tolerance = 1e-5) {
    .Call('_folda_getPillai', PACKAGE = 'folda', Sw, St, tolerance)
}

getWilks <- function(Sw, St, tolerance = 1e-5) {
    .Call('_folda_getWilks', PACKAGE = 'folda', Sw, St, tolerance)
}

qrEigen <- function(A) {
    .Call('_folda_qrEigen', PACKAGE = 'folda', A)
}

svdEigen <- function(A, uFlag = TRUE, vFlag = TRUE) {
    .Call('_folda_svdEigen', PACKAGE = 'folda', A, uFlag, vFlag)
}

